spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xx.xx.xx.xx:3306/bpbase?&useUnicode=true&useSSL=false&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: xxx

  redis:
    host: xx.xx.xx.xx
    port: 6379

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.matej.cache.repository

server:
  port: 8888