spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.riceyo.cn:3306/bpbase?&useUnicode=true&useSSL=false&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: o49mZhodNB9wVKOu

  redis:
    host: www.riceyo.cn
    port: 6381

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.matej.cache.repository

server:
  port: 8888